server:
  port: 8082
spring:
  application:
    name: driver-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: persik
    url: jdbc:postgresql://localhost:5432/driver_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
